### ISSUE TITLE
echoes skill + Multiple hit error

### ISSUE THREAD

**Issue by OldDeusX** [Gktwo/KUN-mod#33]
so just now multiple times had an issue with echoes skill along with multiple hit as some echoes skill that would trigger shatter effect, will causing the game to freeze and not responding such as bell bourne

**Comment by kaiiiru** [comment]
experienced this as well in illusive realm

**Comment by Gktwo** [comment]
Which echo, send image

**Comment by OldDeusX** [comment]
> Which echo, send image

u may close this issue since i think it was error because of multiple hit trigger effect of "shatter" and since it was on highest setting  causing the GPU to overload over second with multiple sfx occurs in time and causing the game to freeze, it was no longer an issue when i dropping the setting to low tho 🤣
