### ISSUE TITLE
Having trouble using the mods

### ISSUE THREAD

**Issue by WoooJenkies** [Gktwo/KUN-mod#60]
I followed the instructions and set the switch, yet nothing happens in game, do I have to do anything with Pak11, and if so which file in Pak11 has to be amended (I tried the Pak11 file you have but that causes the game to not proceed to log in - probably due to wrong Pak11 file/CRC)? Or does this only work with an older version of WuWa?

If you could throw some information my way, that would be appreciated :)

**Comment by OldDeusX** [comment]
1.Place the mod file in the \Wuthering Waves\Wuthering Waves Game\Client\Content\Paks\~mod\
(place the .pak file in the \~mod folder without any sub folder and only the .pak file u are gonna use)

2.find Wuthering Waves\Wuthering Waves Game\Client\Binaries\Win64\Client-Win64-Shipping.exe

3.run game with command line(startupArguments) "-fileopenlog"
( make a shortcut of the Client-Win64-Shipping.exe, then right click - properties - on shortcut TAB pick on Target section and add  -fileopenlog after Client-Win64-Shipping.exe" like Client-Win64-Shipping.exe" -fileopenlog)


what on this part that u don't understand ?

**Comment by WoooJenkies** [comment]
That was a condescending reply, I know how to set a switch in a shortcut, I followed the instructions given and yes even tried with either a ~mod and Paks~mod folder, start the game with shortcut and still nothing.

Unless there is a 3rd party app needed like GIMI?

Otherwise this doesn't work for me, but Pipsi does.

**Comment by Sehyn** [comment]
There is no other software needed, however there is a mod manager that will do all for yourself on my repository.

**Comment by WoooJenkies** [comment]
Thanks for the link I will try it out.

Unfortunately using the tutorial on here doesn't work for myself sadly.

**Comment by WoooJenkies** [comment]
I found out why they weren't working here, I have a download manager installed for Chrome and it wasn't downloading the raw files, but files with html included. So they wouldn't initialise when starting the game.

Now they do. Hopefully people who are having the same problem will be able to use this for help.

**Comment by OldDeusX** [comment]
> I found out why they weren't working here, I have a download manager installed for Chrome and it wasn't downloading the raw files, but files with html included. So they wouldn't initialise when starting the game.
> 
> Now they do. Hopefully people who are having the same problem will be able to use this for help.

wow that mean u using the file without checking the extension, that something...

**Comment by WoooJenkies** [comment]
The extension was .pak it had included html in among the code as if you save from the link to the files here. Once again you assumed something wrong, and looked like a twat in the process.
